### ISSUE TITLE
Request for pretrained model

### ISSUE THREAD

**Issue by Beniko95J** [ActiveVisionLab/nope-nerf#1]
Hi, thank you for open-soucing your great work.

May I ask whether there is a plan to release your pretrained models for evaluation?

**Comment by bianwenjing** [comment]
Hi, thanks for your interest in our work. You can now download the pretrained models on Tanks and Temples through [this link](https://www.robots.ox.ac.uk/~wenjing/pretrained_Tanks.zip). Please note that the models are from different runs so the evaluation results may be slightly different from what we report on the paper.

**Comment by Beniko95J** [comment]
Thank you for the quick reply!
