### ISSUE TITLE
Thanks for your code, could you tell us how to generate the point cloud?Thank you for your respond

### ISSUE THREAD

**Issue by Huhaobangbangbang** [ActiveVisionLab/nope-nerf#15]

**Comment by bianwenjing** [comment]
Hi, the point clouds are generated by unprojecting the depth maps to 3D. Please refer to [link](https://github.com/ActiveVisionLab/nope-nerf/blob/2923f2a3f6f7575647dead408d279be61e7e5c8a/model/training.py#L322C14-L322C14).

**Comment by Huhaobangbangbang** [comment]
Hi, thanks for your respond.
