### ISSUE TITLE
How to visualize poses without gt?

### ISSUE THREAD

**Issue by heyicheng-never** [ActiveVisionLab/nope-nerf#17]
Thanks for your work!

I used a KITTI sequence to train nope-nerf without ground truth poses. When I run the evaluation_pose.py to visualize trajectory, I face an error,
**AttributeError: 'DataField' object has no attribute 'c2ws'**

It seem that I need to provide gt poses to visualize trajectory?

**Comment by bianwenjing** [comment]
Hi, thanks for your interest in our work. I have added `vis/vis_poses.py` for visualising the estimated poses.
