### ISSUE TITLE
Question about the inconsistence of depth

### ISSUE THREAD

**Issue by lbh666** [ActiveVisionLab/nope-nerf#21]
Hi, thanks for your great work!
And I have a question about the detail of your implementation. As shown in the attached image, the depth estimated by nerf usually refer to the range between object and camera. But the DPT depth output is the perpendicular distance between object and camera plane (the definition of depth). Did you consider the difference between them?
Please correct me if I were wrong. Looking forward to your early reply.
![machines1000183g002-622803161b723](https://github.com/ActiveVisionLab/nope-nerf/assets/60417779/2a58c5ee-29dd-41d8-a6e2-38bf722314d9)

**Comment by bianwenjing** [comment]
Hi, sorry for my late reply. The difference between depth (perpendicular distance) and distance(the actual range) is considered. During training, the depth value of DPT is changed to distance at [https://github.com/ActiveVisionLab/nope-nerf/blob/47c861f6259fb0f3921be3a19385feebfa769325/model/rendering.py#L60C12-L60C12](https://github.com/ActiveVisionLab/nope-nerf/blob/47c861f6259fb0f3921be3a19385feebfa769325/model/rendering.py#L60C12-L60C12). The ray vector of NeRF is also normalised, so they should be consistent.

**Comment by lbh666** [comment]
Got It, Thanks!
