### ISSUE TITLE
how to avoid use colmap to generate poses_bounds.npy and use it by load_colmap_poses?

### ISSUE THREAD

**Issue by yuedajiong** [ActiveVisionLab/nope-nerf#7]
as title

**Comment by bianwenjing** [comment]
Hi, you can set `cfg['dataloading']['load_colmap_poses']` to False to avoid loading `poses_bounds.npy`. However, for pose evaluation, you still need the ground truth poses to be loaded in other forms.

**Comment by yuedajiong** [comment]
got it.
a suggestion, need not load ANY pose;  and while no pose/colmap, just ignore evaluation.
