### ISSUE TITLE
Performance on Synthetic_NeRF dataset

### ISSUE THREAD

**Issue by leo-frank** [ActiveVisionLab/nope-nerf#9]
Hi, author ,thanks for your work.

I wonder nopenerf's performance on Synthetic_NeRF dataset (For example, widely-used Lego), had you test on that dataset ? I don't find results in your paper.

**Comment by bianwenjing** [comment]
Hi, thanks for your interest in our work.
We have not tested on the synthetic nerf dataset. During the early stage of our experiments, we found the monocular depth estimation does not perform very well on synthetic datasets, thus we choose to use real-world datasets only.

**Comment by leo-frank** [comment]
Oh, that's resonable. Close it.
